# Generated by Django 5.0.4 on 2024-12-21 13:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cafe",
            fields=[
                (
                    "cafe_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=50)),
                ("addr", models.CharField(max_length=100)),
                ("work_and_study_friendly", models.BooleanField()),
                ("grade", models.CharField(max_length=50)),
                ("time_unlimit", models.BooleanField()),
                ("socket", models.BooleanField(blank=True, null=True)),
                ("pets_allowed", models.BooleanField()),
                ("wiFi", models.BooleanField()),
                ("open_hour", models.CharField(max_length=100)),
                ("open_now", models.BooleanField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("info", models.TextField()),
                ("comment", models.TextField()),
                ("ig_link", models.CharField(blank=True, max_length=500, null=True)),
                ("post_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("ig_post_cnt", models.IntegerField()),
                ("legal", models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MetroStation",
            fields=[
                (
                    "metro_station_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="CafeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="cafe_images/")),
                (
                    "cafe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="cafeInfo.cafe",
                    ),
                ),
            ],
        ),
    ]
