# Generated by Django 5.0.4 on 2024-12-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeInfo', '0002_alter_cafe_legal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='open_hour',
        ),
        migrations.AlterField(
            model_name='cafe',
            name='rating',
            field=models.FloatField(),
        ),
    ]
