# 使用官方 Python 映像
FROM --platform=linux/amd64 python:3.10-slim

# 設置工作目錄
WORKDIR /app

# 創建 logs 目錄
RUN mkdir -p /app/logs

# 複製 requirements.txt 並安裝依賴
COPY ./backend/requirements.txt /app/requirements.txt
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# 複製整個後端目錄到容器
COPY . /app

# 設置環境變量
ENV PYTHONPATH=/app

# 執行 Celery Beat
CMD ["celery", "-A", "mail", "beat", "--loglevel=info"]
