# Generated by Django 5.0.4 on 2024-12-23 18:25

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("email", models.EmailField(blank=True, max_length=50)),
                ("username", models.CharField(blank=True, max_length=20)),
                ("password", models.CharField(blank=True, max_length=30)),
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
