# Generated by Django 5.0.4 on 2024-12-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
