# Generated by Django 5.0.4 on 2024-12-30 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_profile_email_verified"),
        ("user", "0004_remove_profile_date_joined_remove_profile_is_active_and_more"),
    ]

    operations = []
