name: Backend CI/CD Pipeline

on:
    push:
      branches:
        - main  # 當推送到 main 分支時觸發
    pull_request:
      branches:
        - main  # 當 PR 合併到 main 時觸發
  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1. 檢查代碼
    - name: Check out code
      uses: actions/checkout@v3

    # 2. 設置 Python 環境
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.15

    # 3. 安裝依賴
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    # 4. 運行測試
    - name: Run tests
      run: python backend/manage.py test

    # 5. 登錄 Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME_YC }}
        password: ${{ secrets.DOCKER_PASSWORD_YC }}

    # 6. 構建 Docker 映像並推送至 Docker Hub
    - name: Build and Push Docker images
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push

  # 部署至 EC2
  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    # 使用 SSH 登入 EC2
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
            # 停止並移除舊的容器
            docker-compose -f /path/to/docker-compose.yml down || true
            # 拉取最新的 Docker 映像
            docker-compose -f /path/to/docker-compose.yml pull
            # 啟動新的服務容器
            docker-compose -f /path/to/docker-compose.yml up -d
